site_name: Plurality Docs
site_url: https://example.com/

nav:
  - Home: index.md
  - Gov4Git and PMP: Gov4Git and PMP.md
  - Translation Contributor Onboarding: contribute translations to the ⿻ book.md
  - Citation Style Guide: citation style guide.md
  - Style Guide: Style Guide.md

theme:
  name: material