site_name: Plurality Docs
docs_dir: docs


theme:
  name: material
  palette:
    primary: black
  logo: assets/plurality logo.png
  favicon: assets/favicon.png

nav: 
- Start here: 
  - Welcome: index.md
  - Governance and progressive decentralization: home/Home governance and progressive decentralization.md
  - Financial goals: home/Home financial goals.md
  - Copyright: home/Home copyright.md
  - Citing the book: home/Home citing the book.md
 
- Contributing to the project:
  - Getting started: contributing/Contributing getting started as a contributor.md
  - Editing and pull requests: contributing/Contributing editing and pull requests.md
  - Content and edits: contributing/Contributing content and edits.md
  - Translations: contributing/Contributing translations.md
  - Figures and images: contributing/Contributing figures.md
  - Citations and references: contributing/Contributing citations.md
  - Documentation: contributing/Contributing to the docs.md
  - Contributing in other ways: contributing/Contributing in other ways.md

- Book style guide:
  - Style guide introduction: style guide/Style guide introduction.md
  - Book structure: style guide/Style guide book structure.md
  - Punctuation and grammar: style guide/Style guide punctuation and grammar.md
  - Figures: style guide/Style guide figures.md
  - Citations and referencing: style guide/Style guide citations and referencing.md

- Governance of the project:
  - Introduction: governance/Governance introduction.md
  - Plural Credits: governance/Governance plural credits.md
  - Gov4Git: governance/Governance Gov4Git.md
  - Plural Management Protocol: governance/Governance PMP.md
